### PR TITLE
Add support for MPV

### PR DESCRIPTION
**Pull request by Neraste**
This PR adds support for another media player than VLC: `mpv`.

It defines the `media_player` module and `MediaPlayer` abstract class to factorize the common operations between all media players (at the moment, VLC and mpv). Current `VlcPlayer` inherits now from `MediaPlayer` and is renamed `MediaPlayerVlc`. The PR also adds the new class `MediaPlayerMpv` to manage mpv. A thorough refactor of the player objects was made to make this possible and safe.

We use the `python-mpv-jsonipc` to control mpv, as it allows to control a normal release of the player. The package `python-mpv` calls the C API directly and would be preferable, but it requires the dynamic library of the player which is included (strangely enough) only in the dev package of the player. Such package is easily downloaded on Linux, but less on Windows (not with Chocolatey, by instance). Moreover, the package is related to the C API without any backward compatibility: it simply crashes if a requested function does not exist (as in older releases of the player). Given the initial tests we made with this package, it seems the API is not mature enough and changes too often, leading to surprise crashes when using it with this package. The JSON IPC package is less powerful, but more stable.

The current implementation targets mpv 0.32.0, where the IPC API is rather poor: callbacks have no context, by instance, which makes hard to understand what they correspond to. This was a pretty upsetting problem to solve in this PR. A new version of the IPC API, with more context to the callbacks, is currently in the master branch. It should be available in the 0.33.0 version. At this time, it would be neat to update the implementation in `MediaPlayerMpv`. I note that post versions of 0.32.0 (like 0.32.0+gitXXXXXXXXTXXXXXX.XXXXXX) were released on some Linux distributions with this new API already shipped (like OpenSUSE Tumbleweed or Arch Linux), which adds to the confusion.

As the repository does not solely target VLC anymore, it will be renamed `dakara-player` and the command `dakara-play`.

Check list:

* [x] Support MPV;
* [x] Support instrumental tracks;
* [x] Rename project name as `dakara-player` in source code:
  * [x] module name;
  * [x] command name;
  * [x] config file name;
  * [x] Pypi package name;
  * [x] References to repository name and URL;
* [ ] ~Rename repository as `dakara-player`~ (after the PR is merged).

Attributions:
- `MediaPlayerMpv` class and MPV integration: @pjeanjean, @Neraste .
- Modularization of code: @Neraste.

### CODE REVIEW

**Review by Nadeflore — COMMENTED** [review]
A small problem was noticed with the mpv implementation:
the keyboard shortcuts could still be used,
in particular, if a skip forward is used on idle screen, it generate an end reached callback which is not handled and generate an exception.

Also, this particular exception should stop the player (as it is an unexpected state), but currently does not.

Tested with mpv 0.32

**Comment by pjeanjean** [comment]
I will try to have a look this week(end), thank you for all the work to make it usable so far!

**Comment by Neraste** [comment]
@Nadeflore Such kind of exceptions now make the player to crash. Disabling MPV key bindings can be done manually with `--no-input-default-bindings`, but I can't pass this using the current IPC library (version 1.1.13).

**Comment by Neraste** [comment]
I could disable key bindings using the reverse parameter `input_default_bindings = False`.

**Review by Nadeflore — APPROVED** [review]

**Pull request merged**
