### PR TITLE
Fix errors on Windows

### PR DESCRIPTION
**Pull request by Nadeflore**
This PR aims to fix the different bugs of the player on Windows and to create a CI tests process for this platform (with Appveyor).

Bugs fixed:
- [x] Code from Linux font loader was executed causing error at startup;
- [x] The program could not exit (#38);
- [x] Logs were duplicated.

Appveyor CI:
- [x] Setup config file;
- [x] Update readme and so on;
- [ ] Setup DakaraProject account.

### CODE REVIEW

**Comment by Neraste** [comment]
The FontLoaderLinux should not be instanciated at all on a Windows environment. Do not change it as it is not the source of the problem. It seems there is something wrong with the `get_font_loader_class` module function. Please investigate this way.

**Comment by Nadeflore** [comment]
The FontLoaderLinux is not instanciated, it seems this code is executed when loading the fonts_loader file. 
Which makes sense since this is not specific to each instance.

I believe that's the way python load classes.

**Comment by Neraste** [comment]
Ah, true

**Comment by Nadeflore** [comment]
But I do agree this fix is ugly.
My first attempt to fix this was to move the code to the init() method, but this made some tests crash.
maybe we can update the tests for it to work this way.

**Comment by Neraste** [comment]
We can use `os.path.expanduser` in an elegant way I think.

**Comment by Neraste** [comment]
So, this fix allows to keep the two class variables as parameters (as intended), while the actual access to the user directory is processed within the methods.

**Comment by Nadeflore** [comment]
Can't approve my own pr, but I approve of all the changes you made

**Pull request merged**
